config/routes.rb
Rails.application.routes.draw do
  get 'votes/create'

  get 'comments/create'


  resources :questions do
  	resources :answers
    resources :comments
    
    member do
      post 'vote'
    end

  end

  resources :answers do
  	resources :comments

    member do
      post 'vote'
      delete 'vote'
    end
  end

  devise_for :users

  root "questions#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
	belongs_to :question
	belongs_to :user
	has_many :comments, as: :commentable
	has_many :votes, as: :voteable

	validates :body, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :commentable, polymorphic: true
	belongs_to :user

	validates :body, presence: true
end

app/models/question.rb
class Question < ApplicationRecord
	has_many :answers
	has_many :comments
	has_many :comments, as: :commentable
	has_many :votes, as: :voteable
	belongs_to :user

	validates :title, :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :questions
  has_many :answers
  has_many :comments
  has_many :votes
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :creator, class_name: 'User', foreign_key: 'user_id'
  belongs_to :voteable, polymorphic: true

  validates_uniqueness_of :creator, scope: [:voteable_type, :voteable_id]
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def create
    @answer = current_user.answers.new(answer_params)
  	if @answer.save
  		redirect_to question_path(@answer.question)
  	else
  		render 'questions/show'
  	end
  end

  def vote
    @answer = Answer.find(params[:id])
    @question = @answer.question
    case params[:vote]
      when "false"
        @vote = Vote.find_by(voteable_id: params[:id])
        if @vote
          @vote.destroy
          redirect_to question_path(@answer.question)
        else
          @destroy_vote_answer = "No existe un voto a eliminar"
          render "questions/show"
        end
      when "true"
        @vote_answer = @answer.votes.create(user_id: params[:user_id])
        if @vote_answer.save
          redirect_to question_path(@answer.question)  
        else
          @answer_vote_errors = @vote_answer.errors.full_messages
          render "questions/show"
        end
    end
  end

  private

  def answer_params
      params.require(:answer).permit(:body).merge(question_id: params[:question_id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def setMarkDown
	@markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, autolink: true, no_styles: true)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
	@comment = Comment.new(comment_params)
	@comment.user_id = current_user.id
  @question = Question.find(@comment.commentable_id)
  	if @comment.save
  		redirect_to @question
    else
      render 'questions/show'
  	end
  end

  private

  def comment_params
	type = params[:comment][:commentable_type]
  	params.require(:comment).permit(:body, :commentable_type).merge(commentable_id: params["#{type.downcase}_id"])
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_filter :authenticate_user!, :only => :new

  def index
  	@questions = Question.last(8)
      if params[:query] 
        @questions = Question.where("body LIKE :body OR title LIKE :title", body: "%#{params[:query]}%", title: "%#{params[:query]}%")
      end
  end

  def new
  	@question = Question.new
  end

  def create
  	@question = Question.new(question_params)
    @question.user_id = current_user.id
    if @question.save
      redirect_to question_path(@question)
    else
      render :new
    end 

  end

  def show
  	@question = Question.find(params[:id])
  end

  def vote
    @question = Question.find(params[:id])
    case params[:vote]
      when "false"
        @vote = Vote.find_by(voteable_id: params[:id])
        if @vote
          @vote.destroy
          redirect_to question_path(@question)
        else
          @destroy_message = "No existe un voto a eliminar"
          render "questions/show"
        end
      when "true"
        @vote_question = @question.votes.create(user_id: params[:user_id])
        if @vote_question.save
          redirect_to question_path(@question)  
        else
          @vote_errors = @vote_question.errors.full_messages
          render "questions/show"
        end
    end
  end

  private

  def question_params
    params.require(:question).permit(:title, :body)
  end 

end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/answers/_answer.html.erb
<div class="answer-detail">
	<h4><%= answer_counter + 1 %> Answer</h4>
	<p><%= answer.body %></p>
	<div class="row question-user">
		<div class="col-xs-12 col-sm-9 question-user__votes">
			<% if user_signed_in? %>
				<%= link_to vote_answer_path(answer, vote: true, user_id: current_user.id), method: 'post' do %>
			      <i class='up'>up</i>
			    <%end %>
		    <%end %>

			<div class="question-info__item question-info__votes" href="/questions/14">
				<strong><%= answer.votes.count %></strong>
				<span>Votes</span>
			</div>
			
			<% if user_signed_in? %>
			    <%= link_to vote_answer_path(@question, vote: false, user_id: current_user.id), method: 'post' do %>
			      <i class='down'>down</i>
			    <%end %>
			<% end %>
			
			<% if @vote_errors %>
				<p class="votes-error">No puedes votar dos veces lá misma pregunta </p>
		    <% end %>

		    <% if @destroy_message %>
				<p class="votes-error"><%= @destroy_message %></p>
		    <% end %>
		</div>


		<div class="col-xs-12 col-sm-3 question-user__info">
			<span><strong>User:</strong> <%= answer.user.email %></span>
			<span><strong>At:</strong> <%= answer.created_at.strftime("%d/%m/%Y") %></span>
		</div>
	</div>
	<div class="question-user__comments">
		<%= render answer.comments %>
	</div>
	<% if user_signed_in? %>
		<a class="show-comments" href="">Add Comment</a>
	   <%= render partial: 'comments/form', locals: {commentable: answer}%>
	   <% else %>
    	<%= link_to "Add Comment",  user_session_path %>
	<% end %>
</div>

app/views/answers/_form.html.erb
<%= form_for [question, question.answers.new] do |f| %>

<% if @answer.present? && @answer.errors.present? %>
	<div class="errors">
		<p>In order to publish your answer, check the following errors.</p>
		<ul>
		<% @answer.errors.full_messages.each do |error| %>
			<li><%= error %></li>
		<% end %>
		</ul>
	</div>
<% end %>

 <div class="form-group">
   <%= f.label :body, "Write your answer" %>
   <%= f.text_area :body, class: 'form-control input-lg col-sm-2' %>
 </div>

 <div class="actions text-right">
   <%= f.submit "Confirm Question", class:"btn btn-sign-up"  %>
 </div>
<% end %>

app/views/answers/create.html.erb
<h1>Answers#create</h1>
<p>Find me in app/views/answers/create.html.erb</p>

app/views/answers/index.html.erb
<h1>Answers#index</h1>
<p>Find me in app/views/answers/index.html.erb</p>

app/views/answers/show.html.erb
<h1>Answers#show</h1>
<p>Find me in app/views/answers/show.html.erb</p>

app/views/comments/_comment.html.erb
<div class="comment">
	<strong>Comment <%= comment_counter + 1 %></strong>
	<span> | <%= comment.body %></span>
	<span> | <%= comment.user.email %></span>
	<span> | <%= comment.created_at.strftime("%d/%m/%Y") %></span>
</div>

app/views/comments/_form.html.erb
<%= form_for [commentable, commentable.comments.new] do |f| %>

<% if @comment.present? && @comment.errors.present? %>
	<div class="errors">
		<p>In order to publish your comment, check the following errors.</p>
		<ul>
		<% @comment.errors.full_messages.each do |error| %>
			<li><%= error %></li>
		<% end %>
		</ul>
	</div>
<% end %>

 <div class="form-group">
   <%= f.label :body, "Write your comment" %>
   <%= f.text_area :body, class: 'form-control input-lg col-sm-2' %>
   <%= f.hidden_field :commentable_type, value: commentable.class %>
 </div>

 <div class="actions text-right">
   <%= f.submit class: 'btn btn-sign-up comment-submit', style:"margin-bottom: 40px" %>
 </div>
<% end %>

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/new.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Stack</title>
    <%= csrf_meta_tags %>

    <%= favicon_link_tag 'favicon.png' %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Muli:400,700" rel="stylesheet">

  </head>

  <body class="site">
  	<header>
  		<div class="container">
        <div class="row">
          <div class="logo col-sm-2">
            <%= link_to "", root_path %>
          </div>
          <div class="search col-sm-8 text-right">
            <%= form_tag questions_path, method: :get, class: "search" do %>
              <div class="form-group text-right">
                <%= text_field_tag :query, "", class: 'form-control input-search' %>
              </div>
              <%= submit_tag "Buscar", name: nil, class: "btn btn-primary btn-md" %>
            <% end %> 
          </div>
            <div class="user-login col-sm-2 text-center">
            <% if !user_signed_in? %>
              <%= link_to "Log In", user_session_path, class:'btn btn-sign-up' %>
              <% else %>
              <div class="welcome text-right">
                <strong>Welcome</strong>
                <span><%= current_user.email %></span>
                <%= link_to "Sign Out", destroy_user_session_path, :method => :delete %>
              </div>
            <% end %>
            </div>
        </div>
  		</div>
  	</header>
    <% if !user_signed_in? %>
      <div class="invite-join">
        <div class="container">
          <div class="text">
            <p>It's time to code </p>
            <span>StackUp is the largest online community for programmers to learn, share, and solve code problems.
            Create your StackUp account. It's free and only takes a minute.</span>
            <div class="button-wrapper">
              <%= link_to "Sign Up",  new_user_registration_path, class: 'btn btn-sign-up' %>
            </div>
          </div>  
        </div>
      </div>
    <% end %>
    <div class="site-content">
      <%= yield %>
    </div>
    <footer>
      <div class="container">
        <p class="text-center"> © 2017 Stack Up</p>
      </div>
    </footer>
  </body>
</html>

app/views/questions/index.html.erb
<div class="container home">
	<div class="wrapper-title">
		<div class="row">
			<h1 class="col-xs-12 col-sm-6">Latest Questions</h1>
			<div class="button-wrapper button--down col-sm-6">
				<%= link_to "Ask Question", new_question_path, class: 'btn btn-primary'%>
			</div>
		</div>
	</div>

	<ul  class="col-xs-12 col-sm-8 home-questions">
	<% @questions.each do |question| %>
		<li class="home-questions__item row">
			<div class="question-info col-xs-12 col-sm-3">
				<%= link_to question_path(question), class: 'question-info__item question-info__answers' do %>
					<strong><%= question.answers.count %></strong>
					<span>Answers</span>
				<% end %>
				<%= link_to question_path(question), class: 'question-info__item question-info__votes' do %>
					<strong><%= question.votes.count %></strong>
					<span>Votes</span>
				<% end %>
			</div>
			<div class="question-details col-xs-12 col-sm-9">
				<%= link_to "#{question.title}", question_path(question), class: 'home-questions__item__title' %>
				<span class="question-details__user">created by: <%= question.user.email %></span>
				<span class="question-details__date">at: <%=question.created_at.strftime("%d/%m/%Y") %></span> 
			</div>	 
		</li>
	<% end %>
	</ul>	
</div>

app/views/questions/new.html.erb
<div class="container question-form">

	<% if @question.errors.present?  %>
		<div class="errors">
			<p>In order to publish your answer, check the following errors.</p>
			<ul>
			<% @question.errors.full_messages.each do |error| %>
				<li><%= error %></li>
			<% end %>
			</ul>
		</div>
	<% end %>
		
	<p>Thanks for your help</p>
	<p>In the following form you can add a new answer for this question</p>

	<%= form_for @question do |f| %>
	 <div class="form-group">
	 	<%= f.label :title, "Title" %>
	 	<%= f.text_field :title, class: 'form-control input-lg col-sm-2' %>
	</div>
	 <div class="form-group">
	 	<%= f.label :body, "Write your Question" %>
	 	<%= f.text_area :body, class: 'form-control input-lg col-sm-2' %>
	 </div>

	 <div class="actions text-right">
	   <%= f.submit "Post your Question", class:"btn btn-sign-up"  %>
	 </div>
	<% end %>	
</div>

app/views/questions/show.html.erb
<div class="container question-detail">
	<div class="button-wrapper text-right button--down">
	<%= link_to "Ask Question", new_question_path, class: 'btn btn-primary' %>
	</div>
	<h1><%= @question.title %></h1>
	<p><%= @question.body %></p>
	<div class="row question-user">
		<div class="col-xs-12 col-sm-9 question-user__votes">
			<% if user_signed_in? %>
				<%= link_to vote_question_path(@question, vote: true, user_id: current_user.id), method: 'post' do %>
			      <i class='up'>up</i>
			    <%end %>
		    <%end %>

			<div class="question-info__item question-info__votes" href="/questions/14">
				<strong><%= @question.votes.count %></strong>
				<span>Votes</span>
			</div>
			
			<% if user_signed_in? %>
			    <%= link_to vote_question_path(@question, vote: false, user_id: current_user.id), method: 'post' do %>
			      <i class='down'>down</i>
			    <%end %>
			<% end %>
			
			<% if @vote_errors %>
				<p class="votes-error">No puedes votar dos veces lá misma pregunta </p>
		    <% end %>

		    <% if @destroy_message %>
				<p class="votes-error"><%= @destroy_message %></p>
		    <% end %>

		</div>
		<div class="col-xs-12 col-sm-3 question-user__info">
			<span><strong>User:</strong> <%= @question.user.email %></span>
			<span><strong>At:</strong> <%= @question.created_at.strftime("%d/%m/%Y") %></span>
		</div>
	</div>

	<div class="question-user__comments">
		<%= render @question.comments %>
	</div>
	<% if user_signed_in? %>
		<a class="show-comments" href="">Add a Comment</a>
		<%= render partial: 'comments/form', locals: {commentable: @question}%>
	   <% else %>
    	<%= link_to "Add Comment",  user_session_path %>
	<% end %>
	<div class="answers">
		<%= render @question.answers %>
		<% if user_signed_in? %>
		   <%= render partial: 'answers/form', locals: {question: @question}%>
		<% end %>
		<% if !user_signed_in? %>
			<p>Do you want to share your answers?</p>
            <div class="button-wrapper">
              <%= link_to "Sign Up",  new_user_registration_path, class: 'btn btn-sign-up' %>
			<%= link_to "Log In", user_session_path, class:'btn btn-sign-up' %>
            </div>
		<% end %>
	</div>
	
</div>

app/views/votes/_action_vote.html.erb
<%= link_to path(votable, {votable_type: votable.class}), controller: controller, action: action, method: verb, class: 'question-info__item question-info__votes' do %>

        <strong><%= votable.votes.count %></strong>
        <span>Votes</span>
<% end %>

app/views/votes/create.html.erb
<h1>Votes#create</h1>
<p>Find me in app/views/votes/create.html.erb</p>